### ISSUE TITLE
How to access the prisma service from front end or playground if the prisma server is not publicly accessible?

### ISSUE THREAD

**Issue by leopsidom** [akoenig/prisma-kubernetes-deployment#2]
I really like this tutorial. But I am confused about the fact that the prisma server is not exposed to the public, as if this is the case how do I access the service from the front end or playground?

**Comment by akoenig** [comment]
Hi @leopsidom, glad you like it 🎉 So it is intended to not expose the Prisma service to the public. You have to see it as your “database”. There should be an actual GraphQL API in front of it which interacts with your Prisma service and serves as an endpoint for your client / frontend application.

Let me know if you have further questions. Happy to help 🙂

**Comment by leopsidom** [comment]
Hi. Thanks for the reply. I guess I still have a lot to learn. But let's say I run prisma deploy successfully, and it returns an endpoint as http://localhost:4467/hello-world5/dev and great it works. But this is forwarded by my localhost port. If this is in production, I'd like to have an endpoint from the cluster directly, just like prisma development cluster. Am I right? How would I get the endpoint from the cluster in this case?

**Comment by akoenig** [comment]
Ah just forgot to answer your question. Sorry about that 😕

Let’s say you have a Prisma server running on Kubernetes and deployed a Prisma service to it. You would develop an own API which uses [prisma-binding](https://github.com/graphcool/Prisma-binding) for communicating with Prisma. This API would serve as an endpoint for your actual client application and be exposed to the public.
