### ISSUE TITLE
tutorial fails at creating prisma server

### ISSUE THREAD

**Issue by 3nigm4** [akoenig/prisma-kubernetes-deployment#5]
Hello, thank you very much for your tutorial!

I followed every step, but I get a CrashLoop for prisma before the end of your tutorial...
`
kubectl describe pod prisma-qwerty --namespace prisma` returns:

> error syncing pod 

`kubectl logs prisma-qwerty --namespace prisma -p` returns:

> Fatal error during deployment worker initialization: java.sql.SQLSyntaxErrorException: (conn=355) Table 'prisma-mysql.Migration' doesn't exist.

Any ideas?

**Comment by akoenig** [comment]
Hi @3nigm4, you're welcome :slightly_smiling_face: - Hm, I see the described error for the first time. I've just updated the tutorial to work with `Prisma > 1.7`. Would it be possible for you to check if you encounter the problem with the latest Prisma version as well?

**Comment by 3nigm4** [comment]
I ran through again ... it all works for me, thanks!

**Comment by 3nigm4** [comment]
in the last step i would clarify, that you mean the prisma pod not the database pod ...
around this line

> kubectl port-forward --namespace prisma <the-pod-name> 4467:4466 – This will forward from 127.0.0.1:4467 -> kubernetes-cluster:4466

**Comment by 3nigm4** [comment]
oh yeah and one more thing could you show how to add prisma on google cloud platform to:

https://app.prisma.io/_username_/clusters/register-custom !?

**Comment by akoenig** [comment]
@3nigm4 Awesome. Great that it works for you!

Regarding "Connect to a running Prisma server" in Prisma Cloud: Currently only possible if you expose your Prisma server to the Internet via a Kubernetes [Ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/).
